---
version: '3.9'

services:
  api:
    image: triteia-dev
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    environment:
      DB_VENDOR: mariadb
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: triteia
      AMQP_HOST: rabbit
      AMQP_PORT: 5672
    env_file:
      - .env
    volumes:
      - ./src:/srv/app/src
      - ./test:/srv/app/test
    depends_on:
      - db
      - rabbit

  db:
    image: mariadb:10.5
    command: mysqld --bind-address=0.0.0.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_PORT: 3306
      MYSQL_DATABASE: triteia
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 15672:15672
    volumes:
      - ./.rabbitmq_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  db:
